### ISSUE TITLE
Tooltip on input:text focus

### ISSUE THREAD

**Issue by pavelloz** [arashmanteghi/simptip#4]
Hi Arash,

Thank you very much for this clean solution (no js is a big plus for me).

I've been trying to add a tooltip to an input text (instead of placeholder), but it looks like it doesn't work (Fx 22), despite the :focus rules in the code. Im using multiline mode.

According to that snippet:

``` css
   [data-tooltip]:hover:before, [data-tooltip]:hover:after, [data-tooltip]:focus:before, [data-tooltip]:focus:after {
      visibility: visible;
      opacity: 1;
    }
```

I think it should at least show up.

Have you got any idea/suggestion what i could be doing wrong? (I tested on div/span and tooltips are working perfectly).

Regards,
Paweł
